### PR TITLE
Merge Visualization Code into Main

### PR DESCRIPTION
**Pull request by shahbuland**
Overview of changes:
- Created vis folder
- Added PCA visualization of random dataset samples embedded
- Extended above with spherical coordinates
- Copied carp_cloob config (maybe unnecessary?)

### CODE REVIEW

**Comment by LouisCastricato** [comment]
Can you post screenshots of the visualization?

**Comment by LouisCastricato** [comment]
Also can we move this to examples/vis?

**Comment by shahbuland** [comment]
Screenshots posted under vis/figures with annotations, and folder has been moved. UMAP is also integrated now .

**Comment by LouisCastricato** [comment]
LGTM. Can you run black?
Eg
```make style```

You might need to merge from main before you do so though.

**Pull request merged**
